In [28]:
import numpy as np 
import pandas as pd 
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler
import seaborn as sns

#### chargement du jeu de données

In [8]:
data = sns.load_dataset("iris")
X, y = data.drop(columns=["species"], axis=1), data.species
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [19]:
columns = X_train.columns
scaler = StandardScaler()
scaler.fit(X_train, y_train)
X_train = pd.DataFrame(scaler.transform(X_train), columns=columns)

In [21]:
X_test= pd.DataFrame(scaler.transform(X_test), columns=columns)

#### Modélisation

In [23]:
model = GaussianNB()
model.fit(X_train, y_train)
model.score(X_train, y_train)

0.9583333333333334

In [24]:
print("Erreur de géneralisation: ",model.score(X_test, y_test))

Erreur de géneralisation:  0.9666666666666667

In [25]:
model.predict(X_test), y_test

(array(['virginica', 'virginica', 'versicolor', 'setosa', 'versicolor',
        'versicolor', 'virginica', 'setosa', 'versicolor', 'versicolor',
        'versicolor', 'versicolor', 'versicolor', 'virginica', 'setosa',
        'versicolor', 'setosa', 'setosa', 'versicolor', 'versicolor',
        'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor',
        'setosa', 'setosa', 'setosa', 'setosa', 'virginica'], dtype='<U10'),
 116     virginica
 141     virginica
 60     versicolor
 25         setosa
 85     versicolor
 69     versicolor
 130     virginica
 1          setosa
 87     versicolor
 62     versicolor
 71     versicolor
 53     versicolor
 119     virginica
 137     virginica
 7          setosa
 55     versicolor
 33         setosa
 42         setosa
 64     versicolor
 90     versicolor
 142     virginica
 31         setosa
 41         setosa
 94     versicolor
 80     versicolor
 5          setosa
 40         setosa
 15         setosa
 32         setosa
 115     virginica
 Name: species, dtype: object)

In [26]:
X_test

    sepal_length  sepal_width  petal_length  petal_width
0       0.713884    -0.203604      0.926344     0.723501
1       1.181367     0.061966      0.702567     1.368524
2      -1.039174    -2.859303     -0.192542    -0.308536
3      -1.039174    -0.203604     -1.255482    -1.340573
4       0.129532     0.858676      0.366901     0.465492
5      -0.337951    -1.531453      0.031236    -0.179531
6       1.765719    -0.734743      1.262009     0.852505
7      -1.156045    -0.203604     -1.367371    -1.340573
8       0.480143    -2.062593      0.310957     0.078478
9       0.129532    -2.328163      0.087180    -0.308536
10      0.246402    -0.734743      0.087180     0.078478
11     -0.454821    -2.062593      0.087180     0.078478
12      0.129532    -2.328163      0.646622     0.336487
13      0.597014     0.061966      0.926344     0.723501
14     -1.039174     0.858676     -1.311427    -1.340573
15     -0.221080    -0.734743      0.366901     0.078478
16     -0.454821     2.983236     -1.367371    -1.340573
17     -1.740397     0.327536     -1.423315    -1.340573
18     -0.337951    -0.469174     -0.136597     0.078478
19     -0.454821    -1.265883      0.310957    -0.050527
20     -0.104210    -1.000313      0.702567     0.852505
21     -0.571692     0.858676     -1.311427    -1.082564
22     -1.623527    -2.062593     -1.423315    -1.211568
23     -0.337951    -1.000313      0.199068     0.078478
24     -0.454821    -1.797023     -0.024709    -0.179531
25     -0.571692     2.186526     -1.199538    -1.082564
26     -1.039174     1.124246     -1.423315    -1.211568
27     -0.221080     3.514375     -1.311427    -1.082564
28     -0.805433     2.717666     -1.311427    -1.469577
29      0.597014     0.327536      0.814455     1.368524